name: Build Tests

on:
  push:
  pull_request:

jobs:
  demo:
    name: Test demo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes - Push
        id: changes-push
        if: github.event_name != 'pull_request'
        run: |
          git fetch origin ${{ github.ref_name }} --depth=1
          if git diff --quiet origin/${{ github.ref_name }} -- demo; then
            echo "skip=true" >> $GITHUB_ENV
          fi

      - name: Check for changes - Pull Request
        id: changes-pullreq
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          if git diff --quiet origin/${{ github.base_ref }}...HEAD -- demo; then
            echo "skip=true" >> $GITHUB_ENV
          fi

      - name: Set up Node
        if: env.skip != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        if: env.skip != 'true'
        run: npm install

      - name: Run build
        if: env.skip != 'true'
        run: npm run build
