name: Run tests and upload coverage

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run even if no changes are detected'
        required: false
        default: 'false'

jobs:
  sauthbase-js:
    name: Test packages/sauthbase-js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sauthbase-js

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes - Push
        id: changes-push
        if: github.event_name != 'pull_request' && github.event_name != 'workflow_dispatch'
        run: |
          git fetch origin ${{ github.ref_name }} --depth=1
          if git diff --quiet origin/${{ github.ref_name }} -- packages/sauthbase-js; then
            echo "skip=true" >> $GITHUB_ENV
          fi

      - name: Check for changes - Pull Request
        id: changes-pullreq
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          if git diff --quiet origin/${{ github.base_ref }}...HEAD -- packages/sauthbase-js; then
            echo "skip=true" >> $GITHUB_ENV
          fi

      - name: Override skip with manual flag
        if: github.event_name == 'workflow_dispatch' && inputs.force_run == 'true'
        run: echo "skip=false" >> $GITHUB_ENV

      - name: Set up Node
        if: env.skip != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        if: env.skip != 'true'
        run: npm install

      - name: Run tests with coverage
        if: env.skip != 'true'
        run: npm run coverage

      - name: Upload coverage to Codecov
        if: env.skip != 'true'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: scratchcore/sauthbase
          files: ./coverage/lcov.info
          flags: sauthbase-js
          name: sauthbase-js
          verbose: true
