name: Run tests and upload coverage

on: push

jobs:
  sauthbase-js:
    name: Test packages/sauthbase-js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sauthbase-js

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: scratchcore/sauthbase
          files: ./coverage/lcov.info
          flags: sauthbase-js
          name: sauthbase-js
          verbose: true
